### ISSUE TITLE
feature: --dry-run flag

### ISSUE THREAD

**Issue by Fecony** [deaddeno/update#2]
Running code with `--dry-run` flag should return all changes that will be applied without applying them, would be helpful to see what will bet updated
`deno run -Ar https://deno.land/x/update/mod.ts ./deno.json --dry-run`

**Comment by boywithkeyboard** [comment]
@Fecony what about naming the flag `--readonly`?

**Comment by Fecony** [comment]
more like `--outputonly` xd

> @Fecony what about naming the flag `--readonly`?
